branch-defaults:
  master:
    environment: null
global:
  application_name: tasq-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
