"""empty message

Revision ID: 671d1133063f
Revises: e2023735a206
Create Date: 2017-02-26 18:15:20.330932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '671d1133063f'
down_revision = 'e2023735a206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completion_date')
    op.drop_column('tasks', 'notification_date')
    op.add_column('tasks', sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('notification_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'notification_date')
    op.drop_column('tasks', 'completion_date')
    op.add_column('tasks', sa.Column('notification_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
