"""empty message

Revision ID: 738a4c59d290
Revises: 671d1133063f
Create Date: 2017-02-28 13:07:35.107968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738a4c59d290'
down_revision = '671d1133063f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_in', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('text', sa.String(length=80), nullable=False))
    op.drop_column('tasks', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('body', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'text')
    op.drop_column('tasks', 'completed_in')
    # ### end Alembic commands ###
