"""empty message

Revision ID: e2023735a206
Revises: d69c490bc52d
Create Date: 2017-02-19 15:18:49.492213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2023735a206'
down_revision = 'd69c490bc52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('status', sa.String(length=16), nullable=True))
    op.drop_column('invites', 'is_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('invites', 'status')
    # ### end Alembic commands ###
